export const USER_MANUAL_VERSION = "45";
export const USER_MANUAL_UPDATED = "01.09.2026";

export type ManualSection = {
  id: string;
  title: string;
  summary: string;
  platform: "Alle" | "PC" | "Mobil";
  steps: string[];
  tips?: string[];
  keywords: string[];
};

export const userManualSections: ManualSection[] = [
  {
    id: "pilot",
    title: "Pilotbetrieb und Produktionsfreigabe",
    summary: "Warum das Programm bis zum Abschluss aller Firmenprüfungen als Pilot gekennzeichnet ist.",
    platform: "Alle",
    steps: [
      "Die sichtbare Kennzeichnung „Pilot“ bedeutet, dass das Programm bereits getestet wird, aber noch nicht ungeprüft als alleinige Abrechnungsgrundlage verwendet werden darf.",
      "Jedes digitale Aufmaß während des Pilotbetriebs mit einem klassischen Kontrollaufmaß vergleichen.",
      "Abweichungen mit Projekt, Raum, Bauteil, Rechenweg und Ursache dokumentieren.",
      "Erst nach fachlich bestätigten VOB-Regeln, Geräteprüfungen, Backup-/Wiederherstellungsnachweis, Rollen/Rechten und erfolgreichen Baustellentests erfolgt die Produktionsfreigabe.",
    ],
    tips: ["Funktion und Zuverlässigkeit haben Vorrang vor zusätzlichen KI- oder Designfunktionen."],
    keywords: ["pilot", "produktionsreif", "freigabe", "parallelbetrieb", "kontrollaufmaß"],
  },
  {
    id: "quickstart",
    title: "Schnellstart: erstes Aufmaß",
    summary: "Vom neuen Projekt bis zum prüfbaren Export.",
    platform: "Alle",
    steps: [
      "Projekt anlegen und Projektbezeichnung, Auftraggeber, Baustelle, Referenz und Aufnehmer eintragen.",
      "PDF-Grundriss laden oder Räume über Bluetooth-Laser, Handeingabe, Sprache, Skizze oder Insta360 erfassen.",
      "Gewünschte PDF-Seiten sowie Wand, Decke, Boden und Fußleisten auswählen.",
      "Maßstab und erkannte Raumkonturen kontrollieren; unsichere Werte korrigieren.",
      "Öffnungen, Sonderflächen und Materialverbrauch ergänzen.",
      "Im Bereich Prüfen alle Positionen freigeben und anschließend Excel oder PDF exportieren.",
    ],
    tips: ["Gelbe Hinweise müssen kontrolliert werden. Rote Fehler verhindern die Freigabe.", "Ein bereits gefülltes Eingabefeld einfach erneut antippen: Der bisherige Inhalt wird vollständig markiert und durch die nächste Eingabe ersetzt.", "Bei Zahlenfeldern kann der Inhalt vollständig gelöscht werden. Während der Neueingabe wird keine 0 mehr automatisch eingesetzt; eine bewusst eingegebene 0 bleibt davon unterscheidbar."],
    keywords: ["start", "erstes", "projekt", "ablauf", "eingabefeld", "zahlenfeld", "null", "löschen", "ersetzen", "überschreiben"],
  },
  {
    id: "pdf",
    title: "PDF-Grundriss laden, Seiten wählen und zoomen",
    summary: "Große Pläne sicher navigieren und nur ausgewählte Seiten berechnen.",
    platform: "PC",
    steps: [
      "Eine oder mehrere PDF-Dateien gemeinsam auswählen oder auf die Zeichenfläche ziehen. Mehrere PDFs werden in ihrer Auswahlreihenfolge zu einem Plansatz verbunden.",
      "Im Seitenauswahlfenster nur die Grundrissseiten markieren, die in das Aufmaß gehören.",
      "Mit Zoom +/−, Strg beziehungsweise ⌘ plus Mausrad oder Zwei-Finger-Geste vergrößern und verkleinern.",
      "Die HD-Anzeige bestätigt, dass PDF, Maßlinien und Beschriftungen nach jeder Zoomstufe automatisch in Geräteauflösung nachgerendert werden.",
      "Mit einem Finger oder gedrückter linker Maustaste über große Pläne ziehen; das Mausrad scrollt senkrecht, Umschalt plus Mausrad waagerecht.",
      "Die rechte Aufmaßliste besitzt einen eigenen Bildlaufbereich und kann unabhängig vom Grundriss bis zur letzten Position gescrollt werden.",
      "Für jede verwendete Seite Maßstab prüfen oder über eine möglichst lange bekannte Strecke kalibrieren.",
    ],
    tips: ["Ansichten und Schnitte nicht versehentlich mit Grundrissen zusammenrechnen.", "Ohne Maßstab werden nur Maße aus Raumstempel oder Maßketten übernommen.", "Nach schnellem Zoomen kurz warten: Die Seite wird sofort nachgeschärft, ohne den Maßstab oder das Aufmaß zu verändern."],
    keywords: ["pdf", "zoom", "scroll", "mausziehen", "aufmaßliste", "seiten", "maßstab", "kalibrieren", "scharf", "schärfe", "hd", "skalieren"],
  },
  {
    id: "automatic",
    title: "Automatische Grundrisserkennung",
    summary: "Räume, Raumbezeichnungen und Maßketten auch ohne Raumstempel auswerten.",
    platform: "PC",
    steps: [
      "Auto-Aufmaß öffnen, gewünschte Mengen auswählen und eine Standard-Raumhöhe für Räume ohne lesbare Höhenangabe festlegen.",
      "Zu berechnende Seiten markieren und Maßstäbe kontrollieren.",
      "Erkennung starten: Auslesbare Raumbezeichnung und NRF-Fläche werden direkt übernommen. Kräftige, zusammenhängende Wandkörper werden gegenüber dünnen oder gestrichelten Achs-, Maß- und Hilfslinien bevorzugt; eine Kontur wird nur bei eindeutiger, flächenplausibler Zuordnung angezeigt.",
      "Eindeutige Angaben wie „RH 2,75“, „Raumhöhe 2,75 m“ oder „lichte Höhe 2,75“ werden automatisch dem passenden Raum zugeordnet. Angaben aus Schnitt und Ansicht werden nicht übernommen.",
      "Ein gelbes Ausrufezeichen bedeutet „Kontur nicht eindeutig“. Die Software schätzt dann keinen Raumumfang und berechnet weder Wandfläche noch Fußleiste.",
      "Nach dem Auto-Aufmaß bleiben die Räume zunächst nur in der rechten Aufmaßliste sichtbar, damit der Grundriss frei lesbar bleibt.",
      "Einen Raum in der rechten Liste anklicken. Das Programm öffnet automatisch seine PDF-Seite und zeigt ausschließlich diesen Raum mit Kontur, Bezeichnung und Fläche im Grundriss.",
      "Einen anderen Raum anklicken, um die bisherige Markierung vollständig zu ersetzen; es werden niemals alle Raumkonturen gleichzeitig eingeblendet.",
      "Jeden automatisch erkannten Raum rechts anklicken und „Kontur zeichnen“ oder „Kontur korrigieren“ wählen. Eine vorhandene Kontur kann als Ganzes verschoben werden; einzelne Eckpunkte lassen sich separat ziehen. Mit „Neu zeichnen“ kann die Kontur vollständig ersetzt werden. Danach „Abschließen“ wählen; Fläche, Umfang, Wand und Sockel werden neu berechnet.",
      "Erkannte gestrichelte Konturen ebenfalls mit dem Plan vergleichen und bei Bedarf über „Kontur korrigieren“ ersetzen.",
      "Gelbe oder rote Hinweise öffnen und fehlende Maße manuell ergänzen.",
    ],
    tips: ["Die NRF-Fläche darf sicher übernommen sein, obwohl der Raumumfang noch fehlt. Das ist kein Widerspruch: Wandflächen benötigen zusätzlich eine bestätigte Kontur.", "Die Software vergrößert oder erfindet keine Raumkontur, nur damit sie zur NRF-Fläche passt.", "Die Raumkontur verschwindet nicht aus dem Projekt, wenn ein anderer Raum gewählt wird; sie wird nur im Grundriss ausgeblendet.", "Ältere gespeicherte Auto-Konturen werden vorsorglich erneut als ungeprüft markiert; Boden-/Deckenfläche bleibt erhalten, Wand und Sockel benötigen eine neue Konturbestätigung."],
    keywords: ["ki", "automatisch", "raum", "stempel", "maßkette", "erkennung", "kontur", "raumumfang", "gelbes ausrufezeichen"],
  },
  {
    id: "vob",
    title: "VOB-Aufmaß und Öffnungen",
    summary: "Fenster, Türen, Nischen und Abzüge nachvollziehbar behandeln.",
    platform: "Alle",
    steps: [
      "Öffnung dem richtigen Raum zuordnen und Bezeichnung, Breite, Höhe sowie Anzahl eintragen.",
      "Art der Öffnung auswählen: Türen bis einschließlich der eingestellten VOB-Grenze werden übermessen; größere Türen werden vollständig abgezogen.",
      "Wegen der Zarge erhalten Türen unabhängig von ihrer Größe keine Laibungsposition.",
      "Bei Fenstern oder sonstigen Öffnungen die Laibungstiefe eingeben; die Laibung wird 3-seitig aus links, rechts und oben berechnet.",
      "VOB-Grenze anwenden, immer abziehen oder nicht abziehen auswählen.",
      "Bei einer übermessenen Öffnung wird die berechnete Laibung im Prüfnachweis gezeigt, aber nicht zusätzlich zur Wandfläche angesetzt.",
      "Im Rechenweg Bruttofläche, Abzug und Nettofläche kontrollieren.",
      "In den Aufmaß-Einstellungen beziehungsweise mobil in den Projektdaten bestätigen, dass Vertragsgrundlage, vereinbarte ATV-Ausgabe und Übermessungsgrenze fachlich geprüft wurden.",
      "Eine Änderung an Grundlage oder Schwellenwert hebt die Bestätigung automatisch auf und sperrt die Freigabe bis zur erneuten Prüfung.",
    ],
    tips: ["Maßgeblich bleiben Vertrag, Leistungsverzeichnis und vereinbarte ATV. Materialbedarf ist nur eine Kalkulationshilfe."],
    keywords: ["vob", "öffnung", "fenster", "tür", "abzug", "übermessen", "laibung", "leibung"],
  },
  {
    id: "laser",
    title: "Bluetooth-Laser und Handeingabe",
    summary: "Raummaße in der richtigen Reihenfolge erfassen und kontrollieren.",
    platform: "Alle",
    steps: [
      "Laser Bluetooth oder Handeingabe wählen.",
      "Beim Laser Gerät verbinden und Länge, Breite und Höhe nacheinander messen.",
      "Jeden empfangenen Wert dem angezeigten Zielfeld zuordnen und bei Bedarf berichtigen.",
      "Wände, Decke, Boden und Fußleisten auswählen und den Raum übernehmen.",
    ],
    tips: ["Originaler Laserwert und spätere Korrektur bleiben für die Prüfung unterscheidbar.", "Zum Neueingeben ein gefülltes Feld antippen und direkt schreiben; der alte Wert wird automatisch ersetzt."],
    keywords: ["bluetooth", "laser", "leica", "bosch", "länge", "breite", "höhe", "korrigieren", "ersetzen"],
  },
  {
    id: "voice",
    title: "Spracheingabe und KI-Maßassistent",
    summary: "Texte und einzelne Maße gezielt per Sprache eintragen.",
    platform: "Mobil",
    steps: [
      "Mikrofon direkt am gewünschten Feld antippen.",
      "Nur den betreffenden Wert sprechen, zum Beispiel „zwei Meter fünfzig“ oder „Wohnzimmer“.",
      "Erkannten Wert kontrollieren und bei Bedarf überschreiben.",
      "Für komplette Maßfolgen den KI-Maßassistenten verwenden und das Ziel Raum, Öffnung, Skizze oder Sonderfläche prüfen.",
    ],
    tips: ["Beim ersten Einsatz Mikrofonzugriff erlauben. Die Spracheingabe verändert nur das ausgewählte Feld."],
    keywords: ["sprache", "mikrofon", "diktieren", "ki", "maßassistent"],
  },
  {
    id: "sketch",
    title: "Freihandskizze und Apple Pencil",
    summary: "Raumformen zeichnen, automatisch schließen und nachträglich korrigieren.",
    platform: "Mobil",
    steps: [
      "Im Reiter Skizze Raumkontur mit Finger oder Apple Pencil zeichnen.",
      "Beim Zeichnen bleibt die Zeichenfläche fest; Kreuzungen werden automatisch bereinigt und rechtwinklige Raumformen werden begradigt.",
      "Die violette Ergebnisform prüfen: Rechtecke, L-Räume und weitere rechtwinklige Räume werden mit geraden Wänden entlang ihrer erkannten Hauptachsen neu aufgebaut.",
      "Eine bekannte Seite als Referenz messen und die tatsächliche Länge eingeben.",
      "Erkannte Eckpunkte verschieben, hinzufügen oder löschen und Ergebnis übernehmen.",
    ],
    tips: ["Je sauberer die Außenkontur, desto sicherer werden Fläche und Umfang erkannt."],
    keywords: ["skizze", "freihand", "apple pencil", "zeichnen", "kreuzung", "raumform", "begradigen", "l-raum"],
  },
  {
    id: "insta360",
    title: "Insta360-Aufmaß",
    summary: "360°-Aufnahmen projektbezogen dokumentieren und über Kontrollmaße auswerten.",
    platform: "PC",
    steps: [
      "Insta360 öffnen und Panorama im unterstützten Bildformat importieren.",
      "Aufnahme dem Projekt und Raum zuordnen.",
      "Lasermaß oder bekannte Strecke als Referenz eingeben.",
      "Raumform, Maße und Öffnungen kontrollieren und in das Aufmaß übernehmen.",
    ],
    tips: ["Eine 360°-Aufnahme allein liefert ohne bestätigte Referenz keine abrechnungsfähige Länge."],
    keywords: ["insta360", "360", "panorama", "kamera", "kontrollmaß"],
  },
  {
    id: "materials",
    title: "Farbe, Spachtelmasse und Tapete berechnen",
    summary: "Verbrauch, Gebinde, Reserve und Tapetenversatz einstellen.",
    platform: "PC",
    steps: [
      "Excel & Material öffnen und benötigte Materialarten aktivieren.",
      "Verbrauch je Quadratmeter, Anstriche, Gebindegröße und Reserve eingeben.",
      "Bei Tapete Rollenbreite, Rollenlänge und Rapport ohne, gerade oder versetzt auswählen.",
      "Vorschau kontrollieren und anschließend Aufmaß und Materialbedarf exportieren.",
    ],
    tips: ["Die Bestellmenge ist eine Kalkulationshilfe und kein Bestandteil der VOB-Mengenermittlung."],
    keywords: ["farbe", "spachtel", "tapete", "rapport", "versatz", "material", "verbrauch"],
  },
  {
    id: "review",
    title: "Prüfen, freigeben und sperren",
    summary: "Ein prüfbares Aufmaß für Architekt, Auftraggeber und Endkunde erstellen.",
    platform: "Alle",
    steps: [
      "Prüfen öffnen und automatische Fehler sowie Warnungen bearbeiten.",
      "Jede Position freigeben oder als Korrektur markieren.",
      "Prüfer, Büro und digitale Namenszeichnung eintragen.",
      "Prüfen, speichern und sperren wählen. Das Aufmaß erhält Revision und Prüfcode.",
      "Bei späteren Änderungen wird automatisch eine neue bearbeitbare Revision geöffnet.",
    ],
    tips: ["Rote Fehler oder offene Positionen verhindern die Sperrung."],
    keywords: ["prüfen", "freigeben", "sperren", "revision", "prüfcode", "architekt"],
  },
  {
    id: "export",
    title: "Excel, PDF, GAEB und Übergabe",
    summary: "Prüfunterlagen ausgeben und Daten an andere Programme übergeben.",
    platform: "Alle",
    steps: [
      "Prüf-Excel oder PDF-Bericht für farbige Planmarkierungen und Rechenwege wählen.",
      "Prüfprotokoll für Freigaben und Beanstandungen ausgeben.",
      "GAEB-X31-Vorbereitung für die anschließende AVA-Schemaprüfung erstellen.",
      "JSON-Übergabepaket für die spätere Verbindung mit Marcus’ Handwerker-App verwenden.",
    ],
    tips: ["Die X31-Datei ist eine Vorbereitung und muss vor produktivem AVA-Austausch gegen das offizielle Schema geprüft werden."],
    keywords: ["excel", "pdf", "gaeb", "x31", "csv", "json", "export", "marcus"],
  },
  {
    id: "projects",
    title: "Projekte, Archiv, Papierkorb, Versionen und Synchronisierung",
    summary: "Projektakten speichern, Änderungen prüfen, sicher löschen, wiederherstellen und geräteübergreifend öffnen.",
    platform: "Alle",
    steps: [
      "Projekt speichern; Grundriss, Messungen, Prüfstatus und Anlagen werden projektbezogen abgelegt.",
      "Auf Handy und PC mit demselben Konto arbeiten.",
      "Projektliste aktualisieren und dasselbe Projekt öffnen.",
      "Unter Versionen einen älteren Stand auswählen; er wird sicher als neuer Entwurf geöffnet.",
      "Bei paralleler Bearbeitung vergleicht die Speicherung den geladenen Serverstand. Ein fremder neuer Stand wird nicht still überschrieben, sondern als Konflikt gemeldet.",
      "Nicht mehr aktive Projekte über Archivieren aus der laufenden Projektliste entfernen; im Reiter Archiv bleiben sie vollständig erhalten.",
      "Ein archiviertes Projekt mit Wiederherstellen zurück in die aktive Projektliste holen.",
      "Papierkorb wählen, wenn ein Projekt gelöscht werden soll. Aufmaß, Versionen, PDF und 360°-Aufnahmen bleiben mindestens 30 Tage unverändert gespeichert.",
      "Ein aktuell geöffnetes Projekt mit ungespeicherten beziehungsweise noch nicht synchronisierten Änderungen muss vor Archivieren oder Papierkorb zuerst erfolgreich gespeichert werden.",
      "Im Reiter Papierkorb das Projekt kontrollieren und mit Wiederherstellen vollständig in die aktive Projektliste zurückholen.",
      "Im Hauptprogramm über Änderungen den serverseitigen Nachweis öffnen. Dort stehen Benutzer, Zeitpunkt, Aktion sowie alter und neuer Wert fachlich wichtiger Felder.",
    ],
    tips: ["Mobil wird der aktuelle Projektstand bei jeder Änderung auf dem Gerät gesichert. Offline auf „Speichern“ tippen; der Status zeigt „OFFLINE GESICHERT“ und die Übertragung startet nach Rückkehr der Verbindung automatisch.", "Bei einem Synchronisationskonflikt den lokalen Entwurf nicht verwerfen: Serverstand neu laden, Unterschiede prüfen und bewusst zusammenführen.", "Archiv und Papierkorb erfüllen unterschiedliche Aufgaben: Archiv für abgeschlossene Akten, Papierkorb nur für versehentlich oder bewusst entfernte Projekte."],
    keywords: ["projekt", "speichern", "archiv", "archivieren", "papierkorb", "löschen", "änderungsprotokoll", "audit", "version", "wiederherstellen", "synchron", "handy", "pc", "offline"],
  },
  {
    id: "troubleshooting",
    title: "Fehlerhilfe",
    summary: "Die häufigsten Probleme schnell selbst beheben.",
    platform: "Alle",
    steps: [
      "Falsche Raumgröße: Seite und Maßstab prüfen, bekannte Strecke neu kalibrieren und Raumkontur kontrollieren.",
      "Raumkontur falsch oder gelb markiert: Raum in der rechten Liste öffnen, „Kontur zeichnen“ beziehungsweise „Kontur korrigieren“ wählen und die Raumecken im Plan neu setzen.",
      "Keine Raumkontur im Grundriss sichtbar: In der rechten Aufmaßliste den gewünschten Raum anklicken; nur der ausgewählte Raum wird eingeblendet.",
      "Zoom reagiert nicht: Zeichenwerkzeug beenden, Auswahlwerkzeug aktivieren und Zoomtasten, Strg/⌘ plus Mausrad oder Zwei-Finger-Geste verwenden.",
      "Grundriss oder rechte Maße lassen sich nicht bewegen: Mauszeiger über den gewünschten Bereich stellen; den Plan mit gedrückter linker Maustaste ziehen und die Maßliste mit ihrem eigenen Scrollbalken bewegen.",
      "Position fehlt: Prüfen, ob die PDF-Seite ausgewählt und die Position sichtbar ist.",
      "Laser verbindet nicht: Bluetooth aktivieren, Browserberechtigung erlauben, Gerät neu einschalten und erneut verbinden.",
      "App zeigt alte Version: vollständig schließen und neu öffnen; bei Bedarf zum Home-Bildschirm neu laden.",
      "Speichern nicht möglich: Internetverbindung sowie Anmeldung mit demselben Konto prüfen.",
      "Speicherkonflikt: Der Server besitzt einen neueren Stand. Lokalen Geräteentwurf erhalten, Serverstand in einem zweiten Schritt laden und Änderungen kontrolliert zusammenführen.",
    ],
    tips: ["Vor einer Abrechnung immer Prüfbericht und farbige Plananlage kontrollieren."],
    keywords: ["fehler", "problem", "falsch", "zoom", "laser", "speichern", "alte version"],
  },
];
